#This is the world which is protected against grief.
Enabled: true
Protected-world: "world"

#If set to true players are instandly respawned in the Protected-world.
InstandRespawn: true

#Custom Join/Leave messages.
JoinLeaveMessage: true

#Teleport players when they reached LowestY.
VoidTeleport: true
LowestY: 0

#TPA Timeout
tpa-timeout: 60

#The MOTD players will see in the 'Multiplayer' tab.
SystemMotd: "&e➤ &fThis servers is running &6Core {version}"

#These commands are blocked while a player is in vanish.
BlockedCommands:
  - spawn
  - warp
  - gm